baseURL = 'https://mrembiasz.pl'
languageCode = 'en'
title = 'Mateusz Rembiasz'

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Infrastructure, cloud, and self-hosting. Automating everything that shouldn't be done twice."

[taxonomies]
tag = 'tags'
