global:
  imageTag: sha-db40238

frontend:
  image:
    repository: ghcr.io/kerbatek/portfolio-frontend
    pullPolicy: Always
  replicas: 2
  containerPort: 80
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 96Mi

backend:
  image:
    repository: ghcr.io/kerbatek/portfolio-backend
    pullPolicy: Always
  replicas: 2
  containerPort: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  host: example.invalid
  ingressClassName: nginx
  tls: {}
